title = "VimCommands"
baseurl = "http://vimcommands.com"
MetaDataFormat = "yaml"
pluralizeListTitles = false
theme = "command"
paginate = 50

[params]
  Description = "Curated collection of essential Vim commands"
  Keywords = "vim,commands,github,community"
	Author = "Bradley Cicenas"
  Email  = "bradley@vektor.nyc"
