title = "Vim Commands!"
baseurl = "http://vimcommands.com"
MetaDataFormat = "yaml"
pluralizeListTitles = false
theme = "command"
paginate = 30

[params]
	Author = "Bradley Cicenas"
  Email  = "bradley@vektor.nyc"
